### PR TITLE
CRUD

### PR DESCRIPTION
**Pull request by ChrispaixK**
# To-Do list: add & remove

In this PR I :
* Remove all hardcoded items from the tasks array
* Create a new JavaScript file crudop.js for the new functionality
* Implement a function for adding a new task 
* Implement a function for deleting a task
* Implement a function for editing task descriptions.
* Store all CRUD results in the Local Storage

## Below is a loom link as requested by the first code reviewer @zainsadaqat 
https://loom.com/share/3f4646e4aa3141fb8a5c7ed506369d4b

### CODE REVIEW

**Review by zainsadaqat — CHANGES_REQUESTED** [review]
# Required Changes 🔁
# Hello @ChrispaixK  😄 

You're doing a great job on your project. We're proud of you. Good job so far! 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
  ✅  Correct use of Github Flow
  ✅  No linter errors
  ✅  Descriptive Pull Request

## Required Changes ♻️

- [ ] Required functionalities i.e., add and remove items are not working. You will implement the CRUD (create, update, delete) methods. All the user interface elements will be fully functional and the application should be completed at this stage. Kindly take some time to work on the requirements. 😃 👍🏻 

Screenshot 2022-07-07 at 11 13 10 PM

_Check the comments under the review._




## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ChrispaixK** [comment]
# Hello @zainsadaqat  
thanks for reviewing me
I have the impression that you have evaluated my old work and not the recent one

From the branch CRUD the output is as follow
Screenshot from 2022-07-07 21-54-13
This is the home page before adding anything
Screenshot from 2022-07-07 22-00-18
This the UI after adding some task
Screenshot from 2022-07-07 22-06-00
This is a screenshot of the localStorage 

Thank you for your attention @zainsadaqat

**Comment by zainsadaqat** [comment]
## Hey @ChrispaixK 

Great Job! You're good to go. Please submit a request for a second review.

Please share the loom recording here as well.

**Review by omar-muhamad — APPROVED** [review]
# Approved ✔
### Hi @ChrispaixK,

Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

thumbs-up-agree


## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Pull request merged**
